### PR TITLE
Update KillBlock.php

### PR DESCRIPTION
**Pull request by legoboy0215**
WORKS!!!!

### CODE REVIEW

**Comment by deathcrow999** [comment]
Error: Call to undefined method pocketmine\Server::getDefaultWorld()
File: /KillBlock.phar/src/KillBlock/KillBlock
Line: 38
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: KillBlock v1.0.0

Code:
[29]    public $killedByBlock = false;
[30] 
[31]    public function onEnable(){
[32]        $this->getServer()->getPluginManager()->registerEvents($this, $this);
[33]        $this->getLogger()->info(TextFormat::GREEN . "KillBlock has been turned on!!!");
[34]    }
[35] 
[36]    public function onMove(PlayerMoveEvent $event){
[37]        $player = $event->getPlayer();
[38]        $x = $player->getX();
[39]        $y = $player->getY();
[40]        $z = $player->getZ();
[41]        $pos = new Vector3($x, $y - 1, $z);
[42]        $block = $player->getLevel()->getBlock($pos); //Use this method...
[43]         if($block->getId() === Block::get("EMERALD_BLOCK")->getId()){
[44]             $player->teleport(new Vector3($x, $y + 50, $z));
[45]             $this->getLogger()->info(TextFormat::RED . "Teleported! Plugin is working.");
[46]         }
[47]    }
[48] }

**Comment by deathcrow999** [comment]
Isnt there a method getSafeSpawn()?
Instead of getDefaultWorld() we should use getSafeSpawn() that should fix the error i think

**Comment by legoboy0215** [comment]
Wait... Change it into $this->getServer()->getLevelbyName("yourname");

**Comment by legoboy0215** [comment]
BTW, I need to fix a bug.

**Pull request merged**
